import {FormEvent,useMemo,useState} from "react";import {Link,useNavigate} from "react-router-dom";import {ArrowLeft,Check,ShieldCheck} from "lucide-react";import {Button} from "../components/Button";import {useAuth} from "../helpers/useAuth";import styles from "./checkout.module.css";
type Item={productId:number;size:string;quantity:number;name:string;price:number;image:string};const KEY="tt-cart";const read=():Item[]=>{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}};
const countries=[["IN","+91","India"],["AE","+971","UAE"],["US","+1","USA"],["GB","+44","UK"],["AU","+61","Australia"],["CA","+1","Canada"],["SG","+65","Singapore"]];
const states=["Andhra Pradesh","Delhi","Goa","Gujarat","Haryana","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Punjab","Rajasthan","Tamil Nadu","Telangana","Uttar Pradesh","West Bengal","Other"];
type FormData={fullName:string;countryCode:string;phone:string;addressLine1:string;addressLine2:string;city:string;state:string;pincode:string};
export default function CheckoutPage(){const nav=useNavigate();const{authState}=useAuth();const user=authState.type==="authenticated"?authState.user:null;const items=useMemo(read,[]);const total=items.reduce((n,x)=>n+x.price*x.quantity,0);const[address,setAddress]=useState<FormData>({fullName:"",countryCode:"+91",phone:"",addressLine1:"",addressLine2:"",city:"",state:"",pincode:""});const[errors,setErrors]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState("");
const validate=(key?:string)=>{const e:{[k:string]:string}={};const check=(k:string,msg:string,ok:boolean)=>{if(ok===false)e[k]=msg};check("fullName","Enter your full name",/^[A-Za-z][A-Za-z .'-]{1,49}$/.test(address.fullName.trim()));check("phone","Enter a valid mobile number",/^\d{7,15}$/.test(address.phone.replace(/\s/g,"")));check("addressLine1","Enter your delivery address",address.addressLine1.trim().length>=5);check("city","Enter a valid city",/^[A-Za-z][A-Za-z .'-]{1,39}$/.test(address.city.trim()));check("state","Select your state",!!address.state);check("pincode","Enter a valid pincode",/^\d{5,6}$/.test(address.pincode.trim()));const filtered=key?Object.fromEntries(Object.entries(e).filter(([k])=>k===key)):e;setErrors(filtered);return Object.keys(filtered).length===0};
const update=(key:keyof FormData,value:string)=>{setAddress(a=>({...a,[key]:value}));if(errors[key])setErrors(e=>{const n={...e};delete n[key];return n})};
if(!user)return <div className={styles.center}><h1>Ready to checkout?</h1><p>Sign in first so we can keep your order attached to your account.</p><Button asChild><Link to="/login">Login with Google</Link></Button></div>;
if(!items.length)return <div className={styles.center}><h1>Your cart is empty</h1><Button asChild><Link to="/">Shop the drop</Link></Button></div>;
const submit=async(e:FormEvent)=>{e.preventDefault();if(!validate())return;setBusy(true);setError("");try{const shippingAddress={...address,phone:address.countryCode+address.phone.replace(/\s/g,"")};const r=await fetch("/api/orders/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items,shippingAddress})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not place order.");localStorage.removeItem(KEY);window.dispatchEvent(new Event("tt-cart-updated"));nav("/order-success",{state:{orderId:data.order.id,total}})}catch(err){setError(err instanceof Error?err.message:"Could not place order.");setBusy(false)}};
return <div className={styles.page}><header className={styles.header}><Link to="/cart" className={styles.back}><ArrowLeft size={16}/> Back to bag</Link><Link to="/" className={styles.brand}><img src="/_cdn/static/597f09d3-ff67-4eac-98d8-4abad487725a-IMG_6259.jpeg" alt="Traditional Trends official logo"/></Link></header><main className={styles.main}><div><p className={styles.eyebrow}>ALMOST YOURS ✦</p><h1>Make it <em>yours.</em></h1><form onSubmit={submit} noValidate><section className={styles.formSection}><div className={styles.sectionLabel}><span>1</span><h2>Delivery details</h2></div><div className={styles.grid}>
<label className={styles.field}>Full name <span className={styles.required}>*</span><input className={`${styles.fieldInput} ${errors.fullName?styles.fieldError:""}`} value={address.fullName} onChange={e=>update("fullName",e.target.value)} onBlur={()=>validate("fullName")} placeholder="Your name"/>{errors.fullName&&<small className={styles.errorText}>{errors.fullName}</small>}</label>
<label className={styles.field}>Mobile number <span className={styles.required}>*</span><div className={styles.phoneWrap}><select className={styles.countrySelect} value={address.countryCode} onChange={e=>update("countryCode",e.target.value)}>{countries.map(c=><option key={c[0]} value={c[1]}>{c[1]} {c[0]}</option>)}</select><input className={`${styles.fieldInput} ${errors.phone?styles.fieldError:""}`} inputMode="numeric" maxLength={15} value={address.phone} onChange={e=>update("phone",e.target.value.replace(/\D/g,""))} onBlur={()=>validate("phone")} placeholder="98765 43210"/></div>{errors.phone&&<small className={styles.errorText}>{errors.phone}</small>}</label>
<label className={styles.field+" "+styles.wide}>Address line 1 <span className={styles.required}>*</span><input className={`${styles.fieldInput} ${errors.addressLine1?styles.fieldError:""}`} value={address.addressLine1} onChange={e=>update("addressLine1",e.target.value)} onBlur={()=>validate("addressLine1")} placeholder="House / flat, street, area"/>{errors.addressLine1&&<small className={styles.errorText}>{errors.addressLine1}</small>}</label>
<label className={styles.field+" "+styles.wide}>Address line 2 <span>(optional)</span><input className={styles.fieldInput} value={address.addressLine2} onChange={e=>update("addressLine2",e.target.value)} placeholder="Landmark, apartment, etc."/></label>
<label className={styles.field}>City <span className={styles.required}>*</span><input className={`${styles.fieldInput} ${errors.city?styles.fieldError:""}`} value={address.city} onChange={e=>update("city",e.target.value)} onBlur={()=>validate("city")} placeholder="Pune"/>{errors.city&&<small className={styles.errorText}>{errors.city}</small>}</label>
<label className={styles.field}>State <span className={styles.required}>*</span><select className={`${styles.countrySelect} ${errors.state?styles.fieldError:""}`} value={address.state} onChange={e=>update("state",e.target.value)} onBlur={()=>validate("state")}><option value="">Select state</option>{states.map(s=><option key={s}>{s}</option>)}</select>{errors.state&&<small className={styles.errorText}>{errors.state}</small>}</label>
<label className={styles.field}>Pincode <span className={styles.required}>*</span><input className={`${styles.fieldInput} ${errors.pincode?styles.fieldError:""}`} inputMode="numeric" maxLength={6} value={address.pincode} onChange={e=>update("pincode",e.target.value.replace(/\D/g,""))} onBlur={()=>validate("pincode")} placeholder="411001"/>{errors.pincode&&<small className={styles.errorText}>{errors.pincode}</small>}</label>
</div></section>{error&&<p className={styles.error}>{error}</p>}<Button type="submit" size="lg" disabled={busy}>{busy?"Placing your order…":"Place order · ₹"+total.toLocaleString("en-IN")}<Check size={18}/></Button><p className={styles.note}>No payment is required here yet. We'll record your order and delivery details securely.</p></form></div>
<aside className={styles.summary}><div className={styles.summaryTop}><h2>Your bag</h2><small>{items.reduce((n,x)=>n+x.quantity,0)} items</small></div>{items.map(x=><div className={styles.item} key={x.productId+"-"+x.size}><img src={x.image} alt=""/><span>{x.name}<small>Size {x.size} · Qty {x.quantity}</small></span><b>₹{(x.price*x.quantity).toLocaleString("en-IN")}</b></div>)}<div className={styles.total}><span>Total</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><div className={styles.trust}><ShieldCheck size={18}/><span>Your delivery details are used only to process this order. Payment will be added later.</span></div></aside></main></div>}