import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowLeft, Heart, ShoppingBag, User } from "lucide-react";
import { Button } from "../components/Button";
import { getProducts } from "../endpoints/products/list_GET.schema";
import { useAuth } from "../helpers/useAuth";
import styles from "./product.module.css";

const inchMap: Record<number,string> = {34:"XS",36:"S",38:"M",40:"L",42:"XL",44:"2XL",46:"3XL",48:"4XL",50:"5XL",52:"6XL",54:"7XL",56:"8XL"};
function sizesFor(product:any): string[] {
 const raw=String(product?.sizes??"").trim(); if(!raw)return [];
 const available=new Set<string>();
 const add=(s:string)=>{const clean=s.trim().toUpperCase();const value=inchMap[Number(clean)]||clean.replace(/^XXXL$/,"3XL").replace(/^XXL$/,"2XL");if(value)available.add(value)};
 (raw.match(/\b(?:34|36|38|40|42|44|46|48|50|52|54|56)\b/g)??[]).forEach(add);
 (raw.match(/\b(?:XS|S|M|L|XL|XXL|XXXL|[2-8]XL)\b/gi)??[]).forEach(add);
 const labels=Object.values(inchMap);
 const highest=Math.max(...Array.from(available).map(s=>labels.indexOf(s)),0);
 return labels.slice(0,highest+1);
}
function isSizeAvailable(product:any,size:string){const raw=String(product?.sizes??"").toUpperCase();const inch=Object.entries(inchMap).find(([,label])=>label===size)?.[0];return new RegExp('(?:^|\\s|,)(?:'+size.replace('XL','XL')+'|'+(inch||'')+')(?:$|\\s|,)','i').test(raw)}
export default function ProductPage(){
 const [params]=useSearchParams();const {authState}=useAuth();const [products,setProducts]=useState<any[]>([]);const [selected,setSelected]=useState("");const [quantity,setQuantity]=useState(1);const [added,setAdded]=useState(false);const [activeImage,setActiveImage]=useState(0);const [showChart,setShowChart]=useState(false);
 useEffect(()=>{getProducts({cache:"no-store"}).then(r=>{"products" in r&&setProducts(r.products)}).catch(()=>{})},[]);
 const product=products.find(p=>String(p.id)===params.get("id"));const images=useMemo(()=>product?(Array.isArray(product.imageUrls)&&product.imageUrls.length?product.imageUrls:[product.imageUrl].filter(Boolean)):[],[product]);const sizes=sizesFor(product);
 useEffect(()=>{setSelected("");setQuantity(1);setActiveImage(0);setAdded(false)},[product?.id]);
 if(!product)return <main className={styles.page}><header className={styles.header}><Link to="/" className={styles.logo}>traditional<span>trends</span></Link><Link to="/" className={styles.back}><ArrowLeft size={16}/> Back to shop</Link></header><section className={styles.loading}><p>Loading product...</p></section></main>;
 return <div className={styles.page}><header className={styles.header}><Link to="/" className={styles.logo}>traditional<span>trends</span></Link><div className={styles.actions}><Link to="/login" className={styles.account}><User size={19}/>{authState.type==="authenticated"?"Account":"Login"}</Link><Link to="/" className={styles.bag}><ShoppingBag size={20}/></Link></div></header>
 <main className={styles.main}><Link to="/" className={styles.back}><ArrowLeft size={16}/> Back to shop</Link><section className={styles.productPage}>
 <div className={styles.gallery}><div className={styles.mainImage}>{images.length?<img src={images[activeImage]} alt={product.name}/>:<span>No image</span>}</div>{images.length>1&&<div className={styles.thumbs}>{images.map((src:string,i:number)=><button key={i} className={i===activeImage?styles.thumbActive:styles.thumb} onClick={()=>setActiveImage(i)}><img src={src} alt={product.name+" view "+(i+1)}/></button>)}</div>}</div>
 <div className={styles.info}><p className={styles.category}>{product.category}</p><h1>{product.name}</h1>{product.sku&&<p className={styles.sku}>SKU: {product.sku}</p>}<div className={styles.price}>₹{Number(product.price).toLocaleString("en-IN")} {product.oldPrice&&<del>₹{Number(product.oldPrice).toLocaleString("en-IN")}</del>}</div><p className={styles.description}>{product.description||"A thoughtfully crafted piece blending Indian tradition with contemporary style."}</p>{product.fabric&&<p className={styles.detail}><b>Fabric:</b> {product.fabric}</p>}{product.workDetails&&<p className={styles.detail}><b>Work:</b> {product.workDetails}</p>}
 {sizes.length>0&&<div className={styles.sizeSection}><div className={styles.sizeTitle}><b>Size:</b><button type="button" className={styles.chartButton} onClick={()=>setShowChart(true)}>Size Guide</button></div><div className={styles.availableLine}>Only sizes added by the admin are selectable.</div><div className={styles.sizes}>{sizes.map(s=>{const available=isSizeAvailable(product,s);return <button type="button" key={s} disabled={!available} aria-disabled={!available} className={selected===s?styles.sizeSelected:styles.size+(available?"":" "+styles.sizeUnavailable)} onClick={()=>{if(!available)return;setSelected(s);setAdded(false)}}>{s}</button>})}</div><small className={styles.sizeNote}>Choose the label that matches your usual chest measurement.</small></div>}
 {sizes.length===0&&<div className={styles.noSize}><b>Size information unavailable</b><span>Please contact us before ordering so we can confirm the available size.</span></div>}
 <div className={styles.quantity}><b>Quantity</b><div><button type="button" onClick={()=>setQuantity(q=>Math.max(1,q-1))}>−</button><strong>{quantity}</strong><button type="button" onClick={()=>setQuantity(q=>q+1)}>+</button></div></div><div className={styles.stockStatus}>{Number(product.stock)===0?<><b>Currently out of stock</b><span>Sizes are shown for reference and ordering will be available when stock is updated.</span></>:<span>In stock</span>}</div><div className={styles.buyBar}><button className={styles.wishlist} type="button" aria-label="Add to wishlist"><Heart size={24}/></button><Button size="lg" className={styles.add} disabled={Number(product.stock)===0||(sizes.length>0&&!selected)} onClick={()=>{const key="tt-cart";const cart=JSON.parse(localStorage.getItem(key)||"[]");const size=selected||"ONE SIZE";const existing=cart.find((item:any)=>item.productId===product.id&&item.size===size);if(existing)existing.quantity+=quantity;else cart.push({productId:product.id,size,quantity,name:product.name,price:Number(product.price),image:(images[0]||product.imageUrl||"")});localStorage.setItem(key,JSON.stringify(cart));window.dispatchEvent(new Event("tt-cart-updated"));setAdded(true)}}><ShoppingBag size={18}/>{added?"Added"+(selected?" · "+selected:"")+" to bag":"Add to bag"}</Button></div>{sizes.length>0&&!selected&&<p className={styles.chooseNote}>Please select a size to continue.</p>}{added&&<div className={styles.success}>✓ Added to bag as a guest or signed-in customer. <Link to="/login">Sign in</Link> anytime to keep your bag and wishlist synced.</div>}<div className={styles.loginNote}><Heart size={17}/><span>You can browse and shop as a guest. <Link to="/login">Log in</Link> to save your wishlist and keep your account synced.</span></div>
 </div></section></main>{showChart&&<div className={styles.chartBackdrop} onClick={()=>setShowChart(false)}><section className={styles.chartModal} onClick={e=>e.stopPropagation()}><div className={styles.chartHead}><div><p className={styles.category}>SIZE GUIDE</p><h2>Find your size</h2></div><button type="button" className={styles.chartClose} onClick={()=>setShowChart(false)}>×</button></div><p className={styles.chartIntro}>Measure around the fullest part of your bust/chest and choose the closest measurement.</p><div className={styles.chartTable}><div><b>Measurement</b><b>Size</b></div>{[[34,"XS"],[36,"S"],[38,"M"],[40,"L"],[42,"XL"],[44,"2XL"],[46,"3XL"],[48,"4XL"],[50,"5XL"],[52,"6XL"],[54,"7XL"],[56,"8XL"]].map(([inch,label])=><div key={String(inch)}><span>{inch} in</span><span>{label}</span></div>)}</div><Button onClick={()=>setShowChart(false)}>Got it</Button></section></div>}</div>;
}